# Generated by Django 4.2.7 on 2023-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('checkout_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(default='1', max_length=100)),
                ('checkout_Amount', models.IntegerField()),
                ('checkout_Coursename', models.CharField(default='Tên khóa học mặc định', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('thanh_cong', 'Thành công')], default='chua_xac_nhan', max_length=20)),
            ],
        ),
    ]
