# Generated by Django 4.2.7 on 2023-11-27 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('image_course', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('banner_course', models.ImageField(blank=True, null=True, upload_to='course_banners/')),
                ('address_course', models.CharField(choices=[('phong101', 'phòng 101'), ('phong102', 'phòng 102'), ('phong103', 'phòng 103'), ('phong104', 'phòng 104'), ('phong105', 'phòng 105'), ('phong106', 'phòng 106'), ('phong107', 'phòng 107'), ('phong108', 'phòng 108'), ('phong109', 'phòng 109'), ('phong110', 'phòng 110')], default='phong101', max_length=30)),
                ('schedule_course', models.CharField(choices=[('thu 2', 'Thứ 2'), ('thu 3', 'Thứ 3'), ('thu 4', 'Thứ 4'), ('thu 5', 'Thứ 5'), ('thu 6', 'Thứ 6'), ('thu 7', 'Thứ 7'), ('chunhat', 'Chủ nhật')], default='thu 2', max_length=30)),
                ('time_course', models.CharField(choices=[('08:00 - 09:00', '08:00 - 09:00'), ('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('13:30 - 14:30', '13:30 - 14:30'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00'), ('18:30 - 19:30', '18:30 - 19:30'), ('19:00 - 20:00', '19:00 - 20:00'), ('20:00 - 21:00', '20:00 - 21:00'), ('21:00 - 22:00', '21:00 - 22:00')], default='08:00 - 09:00', max_length=50)),
                ('duration_course', models.CharField(choices=[('1thang', '1 tháng'), ('2thang', '2 tháng'), ('3thang', '3 tháng'), ('6thang', '6 tháng')], default='1thang', max_length=30)),
                ('description_course', models.TextField(blank=True, max_length=500, null=True)),
                ('tuition_course', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_member', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(choices=[('1thang', '1 tháng'), ('2thang', '2 tháng'), ('3thang', '3 tháng'), ('6thang', '6 tháng')], max_length=40, verbose_name='Duration')),
                ('schedule', models.CharField(choices=[('thu 2', 'Thứ 2'), ('thu 3', 'Thứ 3'), ('thu 4', 'Thứ 4'), ('thu 5', 'Thứ 5'), ('thu 6', 'Thứ 6'), ('thu 7', 'Thứ 7'), ('chunhat', 'Chủ nhật')], max_length=40, verbose_name='Schedule')),
                ('time', models.CharField(choices=[('08:00 - 09:00', '08:00 - 09:00'), ('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('13:30 - 14:30', '13:30 - 14:30'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00'), ('18:30 - 19:30', '18:30 - 19:30'), ('19:00 - 20:00', '19:00 - 20:00'), ('20:00 - 21:00', '20:00 - 21:00'), ('21:00 - 22:00', '21:00 - 22:00')], max_length=40, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.membership')),
            ],
        ),
    ]
